
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class AdminPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPage.class.getName());

    /**
     * Creates new form AdminPage
     */
    public AdminPage(String username) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jLabelUsernameAdmin.setText(username);
        tampilDaftarBuku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelUsernameAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDaftarBuku = new javax.swing.JTable();
        jLabelLogoutMouseClicked = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldJudul = new javax.swing.JTextField();
        jTextFieldPenerbit = new javax.swing.JTextField();
        jTextFieldPengarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTahun = new javax.swing.JTextField();
        jTextFieldJumlah = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jLabelLogout.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 0, 0));
        jLabelLogout.setText("Logout");
        jLabelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda Admin");
        setBackground(new java.awt.Color(153, 153, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(240, 231, 220));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 102, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hi,");
        jLabel7.setToolTipText("");

        jLabelUsernameAdmin.setBackground(new java.awt.Color(240, 220, 220));
        jLabelUsernameAdmin.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabelUsernameAdmin.setForeground(java.awt.Color.darkGray);
        jLabelUsernameAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableDaftarBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Buku_id", "Judul", "Pengarang", "Penerbit", "Tahun terbit", "Kategori", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableDaftarBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDaftarBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDaftarBuku);

        jLabelLogoutMouseClicked.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabelLogoutMouseClicked.setForeground(new java.awt.Color(255, 51, 51));
        jLabelLogoutMouseClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-logout-24.png"))); // NOI18N
        jLabelLogoutMouseClicked.setText("Logout");
        jLabelLogoutMouseClicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClickedMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Judul");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pengarang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penerbit");

        jTextFieldJudul.addActionListener(this::jTextFieldJudulActionPerformed);

        jTextFieldPenerbit.addActionListener(this::jTextFieldPenerbitActionPerformed);

        jTextFieldPengarang.addActionListener(this::jTextFieldPengarangActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tahun");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kategori");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah");

        jTextFieldTahun.addActionListener(this::jTextFieldTahunActionPerformed);

        jTextFieldJumlah.addActionListener(this::jTextFieldJumlahActionPerformed);

        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-pencil-24.png"))); // NOI18N
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-trash-32.png"))); // NOI18N
        jButtonDelete.setToolTipText("");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIlilh Kategori" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPenerbit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxKategori)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)
                        .addGap(6, 6, 6)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogoutMouseClicked)
                .addGap(28, 28, 28))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelLogoutMouseClicked)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 600, 450));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bookshelves4.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 850, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJudulActionPerformed

    private void jTextFieldPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenerbitActionPerformed

    private void jTextFieldPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPengarangActionPerformed

    private void jTextFieldTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTahunActionPerformed

    private void jTextFieldJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJumlahActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int barisDipilih = jTableDaftarBuku.getSelectedRow();       
        int idBuku = Integer.parseInt(jTableDaftarBuku.getValueAt(barisDipilih, 0).toString());
        DefaultTableModel  model = (DefaultTableModel) jTableDaftarBuku.getModel();
        
        Connection con = MyConnection.getConnection();
        try {          
            String sqlDeleteData = "DELETE FROM buku WHERE buku_id = ?";
            PreparedStatement statementDeleteData = con.prepareStatement(sqlDeleteData);
            statementDeleteData.setInt(1, idBuku);
            
            int berhasilDeleteData = statementDeleteData.executeUpdate();
            
            if (berhasilDeleteData > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Message", JOptionPane.INFORMATION_MESSAGE);
                model.setRowCount(0);
                tampilDaftarBuku();
                jTextFieldJudul.setText("");
                jTextFieldPengarang.setText("");
                jTextFieldPenerbit.setText("");
                jTextFieldTahun.setText("");
                jComboBoxKategori.setSelectedItem("Pilih Kategori"); 
                jTextFieldJumlah.setText("");       
            }
        
        } catch (SQLException ex) {           
         System.err.print("gagal delete buku: " + ex.getMessage());
         JOptionPane.showMessageDialog(this, "gagal delete data!", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void jLabelLogoutMouseClickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClickedMouseClicked
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(this, "Apakah kamu yakin ingin keluar dari akun?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (pilih == JOptionPane.YES_OPTION) {       
            LoginForm halamanLogin = new LoginForm();
            halamanLogin.setVisible(true);

            this.dispose(); 
        }  
    }//GEN-LAST:event_jLabelLogoutMouseClickedMouseClicked

    private void jTableDaftarBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDaftarBukuMouseClicked
        // TODO add your handling code here:
        int barisDipilih = jTableDaftarBuku.getSelectedRow();

        if (barisDipilih == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dari table dahulu!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        String judul = jTableDaftarBuku.getValueAt(barisDipilih, 1).toString();
        String pengarang = jTableDaftarBuku.getValueAt(barisDipilih, 2).toString();
        String penerbit = jTableDaftarBuku.getValueAt(barisDipilih, 3).toString();
        String tahun = jTableDaftarBuku.getValueAt(barisDipilih, 4).toString();
        String kategori = jTableDaftarBuku.getValueAt(barisDipilih, 5).toString();
        String jumlah = jTableDaftarBuku.getValueAt(barisDipilih, 6).toString();
        
        jTextFieldJudul.setText(judul);
        jTextFieldPengarang.setText(pengarang);
        jTextFieldPenerbit.setText(penerbit);
        jTextFieldTahun.setText(tahun);
        jComboBoxKategori.setSelectedItem(kategori); 
        jTextFieldJumlah.setText(jumlah);  
    }//GEN-LAST:event_jTableDaftarBukuMouseClicked

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        int barisDipilih = jTableDaftarBuku.getSelectedRow();
        
        if (barisDipilih == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dari table dahulu!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        DefaultTableModel  model = (DefaultTableModel) jTableDaftarBuku.getModel();
        
        int id = Integer.parseInt(jTableDaftarBuku.getValueAt(barisDipilih, 0).toString());
        String judul = jTextFieldJudul.getText().trim();
        String pengarang = jTextFieldPengarang.getText().trim();
        String penerbit = jTextFieldPenerbit.getText().trim();
        int tahun = Integer.parseInt(jTextFieldTahun.getText().trim());
        String kategori = (String) jComboBoxKategori.getSelectedItem();
        int jumlah = Integer.parseInt(jTextFieldJumlah.getText().trim());
        
        if (judul.isEmpty() || pengarang.isEmpty() || penerbit.isEmpty() || jTextFieldTahun.getText().trim().isEmpty() || kategori.isEmpty() ||jTextFieldJumlah.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua data harus diisi!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        if (judul.equals(jTableDaftarBuku.getValueAt(barisDipilih, 1).toString()) && 
                pengarang.equals(jTableDaftarBuku.getValueAt(barisDipilih, 2).toString()) &&
                penerbit.equals(jTableDaftarBuku.getValueAt(barisDipilih, 3).toString()) &&
                jTextFieldTahun.getText().trim().equals(jTableDaftarBuku.getValueAt(barisDipilih, 4).toString()) &&
                kategori.equals(jTableDaftarBuku.getValueAt(barisDipilih, 5).toString()) &&
                jTextFieldJumlah.getText().trim().equals(jTableDaftarBuku.getValueAt(barisDipilih, 6).toString())
                ) {
        JOptionPane.showMessageDialog(this, "Data belum diubah!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        Connection con = MyConnection.getConnection();
        
        try {
            String sqlUpdateData = "UPDATE buku SET judul = ?, pengarang = ?, penerbit = ?, tahun_terbit = ?, kategori = ?, jumlah = ? WHERE buku_id = ?";
            PreparedStatement statementUpdateData = con.prepareStatement(sqlUpdateData);
            statementUpdateData.setString(1, judul);
            statementUpdateData.setString(2, pengarang);
            statementUpdateData.setString(3, penerbit);
            statementUpdateData.setInt(4, tahun);
            statementUpdateData.setString(5, kategori);
            statementUpdateData.setInt(6, jumlah);
            statementUpdateData.setInt(7,id);
            
            int berhasilUpdateData = statementUpdateData.executeUpdate();
            
            if (berhasilUpdateData > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate!", "Message", JOptionPane.INFORMATION_MESSAGE);
                model.setRowCount(0);
                tampilDaftarBuku();
                jTextFieldJudul.setText("");
                jTextFieldPengarang.setText("");
                jTextFieldPenerbit.setText("");
                jTextFieldTahun.setText("");
                jComboBoxKategori.setSelectedItem("Pilih Kategori"); 
                jTextFieldJumlah.setText("");
            }
            
        } catch (SQLException ex) {           
         System.err.print("gagal mengupdate buku: " + ex.getMessage());
         JOptionPane.showMessageDialog(this, "gagal melakukan update!", "Message", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonEditActionPerformed

    private void tampilDaftarBuku() {
                
        DefaultTableModel  model = (DefaultTableModel) jTableDaftarBuku.getModel(); 
        model.setColumnCount(0);
        model.addColumn("ID");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Kategori");
        model.addColumn("Jumlah");
     
        Connection con = MyConnection.getConnection();
        
        try {
            String sqlListBuku = "SELECT buku_id, judul, pengarang, penerbit, tahun_terbit, kategori, jumlah FROM buku";
            PreparedStatement statementListBuku = con.prepareStatement(sqlListBuku);
            ResultSet resListBuku = statementListBuku.executeQuery();
            
            while (resListBuku.next()) {
               model.addRow(new Object[]{
                   resListBuku.getInt("buku_id"),
                   resListBuku.getString("judul"),
                   resListBuku.getString("pengarang"),
                   resListBuku.getString("penerbit"),
                   resListBuku.getInt("tahun_terbit"),
                   resListBuku.getString("kategori"),
                   resListBuku.getInt("jumlah"),
               }); 
            }
            
            String sqlListKategoriBuku = "SELECT DISTINCT kategori FROM buku WHERE kategori IS NOT NULL ORDER BY kategori ASC";
            PreparedStatement statementListKategoriBuku = con.prepareStatement(sqlListKategoriBuku);
            ResultSet resListKategoriBuku = statementListKategoriBuku.executeQuery();
            
            jComboBoxKategori.removeAllItems();
            jComboBoxKategori.addItem("Pilih Kategori");
            
            while(resListKategoriBuku.next()){
            jComboBoxKategori.addItem(resListKategoriBuku.getString("kategori"));
            }
            
        } catch (SQLException ex) {
            System.err.print("gagal memuat buku: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal memuat data ke sistem: " + ex.getMessage(), "Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminPage("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<String> jComboBoxKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelLogoutMouseClicked;
    private javax.swing.JLabel jLabelUsernameAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDaftarBuku;
    private javax.swing.JTextField jTextFieldJudul;
    private javax.swing.JTextField jTextFieldJumlah;
    private javax.swing.JTextField jTextFieldPenerbit;
    private javax.swing.JTextField jTextFieldPengarang;
    private javax.swing.JTextField jTextFieldTahun;
    // End of variables declaration//GEN-END:variables
}
