
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class RegisterForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterForm.class.getName());

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelLogin = new javax.swing.JPanel();
        jLabelUsernameRegister = new javax.swing.JLabel();
        jLabelPasswordRegister = new javax.swing.JLabel();
        jPasswordRegister = new javax.swing.JPasswordField();
        jTextUsernameRegister = new javax.swing.JTextField();
        jCheckBoxShowPasswordRegister = new javax.swing.JCheckBox();
        jButtonRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Page");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        jLabel2.setText("already have an account? ");

        jLabelRegister.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(153, 102, 0));
        jLabelRegister.setText("Register");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 102, 0));
        jLabel3.setText("Login");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanelLogin.setBackground(new java.awt.Color(240, 231, 210));
        jPanelLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        jLabelUsernameRegister.setText("username");

        jLabelPasswordRegister.setText("password");

        jPasswordRegister.addActionListener(this::jPasswordRegisterActionPerformed);

        jTextUsernameRegister.addActionListener(this::jTextUsernameRegisterActionPerformed);

        jCheckBoxShowPasswordRegister.setText("show password");
        jCheckBoxShowPasswordRegister.addActionListener(this::jCheckBoxShowPasswordRegisterActionPerformed);

        jButtonRegister.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(this::jButtonRegisterActionPerformed);

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsernameRegister, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPasswordRegister, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextUsernameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jPasswordRegister)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLoginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBoxShowPasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsernameRegister)
                    .addComponent(jTextUsernameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordRegister)
                    .addComponent(jPasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxShowPasswordRegister)
                    .addComponent(jButtonRegister))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabelRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bookshelves2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsernameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsernameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsernameRegisterActionPerformed

    private void jCheckBoxShowPasswordRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswordRegisterActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxShowPasswordRegister.isSelected()) {
            jPasswordRegister.setEchoChar((char)0);
        } else {
            jPasswordRegister.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPasswordRegisterActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        
    String username = jTextUsernameRegister.getText();
    String password = String.valueOf(jPasswordRegister.getPassword());

    if (username.trim().equals("") || password.trim().equals("")) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    if (password.length() < 8) {
        JOptionPane.showMessageDialog(this, "Password minimal 8 karakter!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    Connection con = MyConnection.getConnection();
    String sqlCheckUsername = "SELECT * FROM users WHERE username = ?";
    String sqlAddUser = "INSERT INTO users (username, password) VALUES (?, ?)";
   
        try {
            PreparedStatement statementUserName = con.prepareStatement(sqlCheckUsername);            
            statementUserName.setString(1, username); 
            
            ResultSet resUsername = statementUserName.executeQuery();

            if (resUsername.next()) {
               JOptionPane.showMessageDialog(this, "Username sudah digunakan!", "Message", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

        } catch (SQLException ex) {
            System.err.println("Error saat cek username: " + ex.getMessage());
            return;
        }
   
        try {
            PreparedStatement statementAddUser = con.prepareStatement(sqlAddUser);

            statementAddUser.setString(1, username);
            statementAddUser.setString(2, password);

            int barisTersimpan = statementAddUser.executeUpdate();

            if (barisTersimpan > 0) {
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil!", "Message", JOptionPane.INFORMATION_MESSAGE);
                jTextUsernameRegister.setText("");
                jPasswordRegister.setText("");
            }
            
        } catch (SQLException ex) {
            System.err.println("Error saat register: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Registrasi Gagal: " + ex.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPasswordRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterForm().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JCheckBox jCheckBoxShowPasswordRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPasswordRegister;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelUsernameRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordRegister;
    private javax.swing.JTextField jTextUsernameRegister;
    // End of variables declaration//GEN-END:variables
}
