import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class UserPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserPage.class.getName());

    /**
     * Creates new form UserPage
     */
    public UserPage(String username) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jLabelUsernameUserPage.setText(username);
        tampilJudulBukuComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelUsernameUserPage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBukuTersedia = new javax.swing.JComboBox<>();
        jTextFieldJumlahBuku = new javax.swing.JTextField();
        jButtonPinjamBuku = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserKembali = new com.toedter.calendar.JDateChooser();
        jLabelLogout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-leaves-64.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda User");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(240, 231, 210));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));

        jLabelUsernameUserPage.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabelUsernameUserPage.setForeground(java.awt.Color.darkGray);
        jLabelUsernameUserPage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hi,");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsernameUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsernameUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13))
        );

        jPanel2.setBackground(new java.awt.Color(240, 231, 210));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 2, true));

        jLabel1.setText("Buku yang tersedia");

        jLabel2.setText("Jumlah Buku");

        jComboBoxBukuTersedia.addActionListener(this::jComboBoxBukuTersediaActionPerformed);

        jTextFieldJumlahBuku.addActionListener(this::jTextFieldJumlahBukuActionPerformed);

        jButtonPinjamBuku.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        jButtonPinjamBuku.setText("Pinjam");
        jButtonPinjamBuku.addActionListener(this::jButtonPinjamBukuActionPerformed);

        jLabel3.setText("Tanggal Kembali");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxBukuTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPinjamBuku)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooserKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxBukuTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPinjamBuku))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabelLogout.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 0, 0));
        jLabelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-logout-24.png"))); // NOI18N
        jLabelLogout.setText("Logout");
        jLabelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-leaves-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLogout))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelLogout))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJumlahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJumlahBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJumlahBukuActionPerformed

    private void jComboBoxBukuTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBukuTersediaActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jComboBoxBukuTersediaActionPerformed

    private void jButtonPinjamBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPinjamBukuActionPerformed
        // TODO add your handling code here:
   
        String bukuDipilih = (String) jComboBoxBukuTersedia.getSelectedItem();
        String userName = jLabelUsernameUserPage.getText();        
     
        if (bukuDipilih.isEmpty() || jTextFieldJumlahBuku.getText().isEmpty() || jDateChooserKembali.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        SimpleDateFormat formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalKembali = formatTanggal.format(jDateChooserKembali.getDate());
        String tanggalPinjam = formatTanggal.format(new Date());                
        
        if (!jTextFieldJumlahBuku.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Jumlah buku harus berupa angka!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        int jumlahBukuDipinjam = Integer.parseInt(jTextFieldJumlahBuku.getText().trim());
  
        if (jumlahBukuDipinjam == 0) {
        JOptionPane.showMessageDialog(this, "Jumlah buku harus lebih dari 0!", "Message", JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        Connection con = MyConnection.getConnection();

        int jumlahBukuTersedia; 
        int idUser = -1;
        int idBuku = -1;
        
        try {
            
            String sqlJumlahBuku = "SELECT jumlah FROM buku WHERE judul = ?";   
            PreparedStatement jumlahBukuStmt = con.prepareStatement(sqlJumlahBuku);
            jumlahBukuStmt.setString(1, bukuDipilih);
            ResultSet resJumlahBuku = jumlahBukuStmt.executeQuery();
            
            if (resJumlahBuku.next()) {               
               jumlahBukuTersedia = resJumlahBuku.getInt("jumlah");
                
                if (jumlahBukuDipinjam > jumlahBukuTersedia) {                   
                 JOptionPane.showMessageDialog(this, "stok buku tidak cukup", "Message", JOptionPane.INFORMATION_MESSAGE);
                 return;                
                }               
            } 
            
            String sqlGetUserId = "SELECT user_id FROM users WHERE username = ?";
            PreparedStatement statementGetUserId = con.prepareStatement(sqlGetUserId);
            statementGetUserId.setString(1, userName);

            ResultSet resGetUserId = statementGetUserId.executeQuery();            

            if (resGetUserId.next()) {
               idUser = resGetUserId.getInt("user_id");
            }
            
            String sqlGetBukuId = "SELECT buku_id FROM buku WHERE judul = ?";
            PreparedStatement statementGetBukuId = con.prepareStatement(sqlGetBukuId);
            statementGetBukuId.setString(1, bukuDipilih);
            
            ResultSet resGetBukuId = statementGetBukuId.executeQuery();
            
            if(resGetBukuId.next()){
                idBuku = resGetBukuId.getInt("buku_id");
            }
            
            if (idUser != -1 && idBuku != -1) {
                String sqlAddPinjaman = "INSERT INTO peminjaman (user_id, buku_id, tanggal_pinjam, tanggal_kembali) VALUES (?, ?, ?, ?)";       
                PreparedStatement statementAddPinjaman = con.prepareStatement(sqlAddPinjaman);
                
                statementAddPinjaman.setInt(1,idUser);
                statementAddPinjaman.setInt(2,idBuku);
                statementAddPinjaman.setDate(3,java.sql.Date.valueOf(tanggalPinjam));
                statementAddPinjaman.setDate(4,java.sql.Date.valueOf(tanggalKembali));
                
                int berhasilAddPinjaman = statementAddPinjaman.executeUpdate();
                
                if (berhasilAddPinjaman > 0) {                    
                    String sqlUpdateJumlahBuku = "UPDATE buku SET jumlah = (jumlah-?) WHERE buku_id = ?";
                    PreparedStatement statementUpdateJumlahBuku = con.prepareStatement(sqlUpdateJumlahBuku);
                    
                    statementUpdateJumlahBuku.setInt(1, jumlahBukuDipinjam);
                    statementUpdateJumlahBuku.setInt(2, idBuku);
                    
                    int berhasilUpdateJumlahBuku = statementUpdateJumlahBuku.executeUpdate();
                    
                    if (berhasilUpdateJumlahBuku > 0) {                       
                        JOptionPane.showMessageDialog(this, "Buku Berhasil Dipinjam!", "Message", JOptionPane.INFORMATION_MESSAGE);                  
                    
                        tampilJudulBukuComboBox(); 
                    
                        jTextFieldJumlahBuku.setText("");
                        jDateChooserKembali.setDate(null);

                    }               
                }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal memproses peminjaman buku!", "Message", JOptionPane.INFORMATION_MESSAGE);
        }             
    }//GEN-LAST:event_jButtonPinjamBukuActionPerformed

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(this, "Apakah kamu yakin ingin keluar dari akun?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (pilih == JOptionPane.YES_OPTION) {       
            LoginForm halamanLogin = new LoginForm();
            halamanLogin.setVisible(true);

            this.dispose(); 
        }        
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void tampilJudulBukuComboBox () {
        Connection con = MyConnection.getConnection();
        String sqlListBuku = "SELECT judul FROM buku";
        
        try {
            PreparedStatement listBuku = con.prepareStatement(sqlListBuku);
            ResultSet resListBuku = listBuku.executeQuery();
            
            while (resListBuku.next()) {
                jComboBoxBukuTersedia.addItem(resListBuku.getString("judul"));
            }
            
        } catch (SQLException ex) {
            System.err.print("gagal memuat buku: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "gagal mendapat daftar buku", "Message", JOptionPane.INFORMATION_MESSAGE);

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> new UserPage("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPinjamBuku;
    private javax.swing.JComboBox<String> jComboBoxBukuTersedia;
    private com.toedter.calendar.JDateChooser jDateChooserKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelUsernameUserPage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldJumlahBuku;
    // End of variables declaration//GEN-END:variables
}
